
class Sensors:
    class ReservoirLevel:
        PRESSURE_SENSOR_FAIL_LOW = 6000
        PRESSURE_SENSOR_FAIL_HIGH = 30000
        PRESSURE_SENSOR_RESERVOIR_FULL_UPPER_LIMIT = 29000
        PRESSURE_SENSOR_RESERVOIR_FULL_LOWER_LIMIT = 24600
        PRESSURE_SENSOR_RESERVOIR_EMPTY = 7000
        PRESSURE_SENSOR_RESERVOIR_RANGE = PRESSURE_SENSOR_RESERVOIR_FULL_UPPER_LIMIT - PRESSURE_SENSOR_RESERVOIR_EMPTY
        K_CONST = 5.0/32000
        ADC_SENSOR_MAX = 5000
        ADC_SENSOR_STEP = 32000 
